global:
   scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
         - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/alerts.yml"            

scrape_configs:
  - job_name: 'loan-app' 
    static_configs:
       - targets: ['loan-app:8080']  





