apiVersion: argoproject.io/v1
kind: Application
metadata: 
    name: demo-app-azure
    namespace: argocd
spec: 
    project: default
    source: 
    repoURL: 'https.github.com/mac-cloud/INFRA-MULTICLOUD'
    path: 'k8s'
    targetRevision: HEAD
destination:
    server: 'azure-demo-cluster-7xic68sc.hcp.eastus.azmk8s.io'
    namespace: demo-app
syncPolicy: 
    automated: 
    prune: true
    selfHeal: true             